// JavaScript Document



equip_characters_list = [
    "elsword",
    "aisha",
    "rena",
    "raven",
    "eve",
    "chung",
    "ara",
    "elesis",
    "add",
    "lu",
    "ciel",
    "rose",
    "ain",
    "laby",
    "noah",
    "lithia"
]


equip_characters = [
    {
        "character": "elsword",
        "class": "elsword",
        "class_name": "Elsword",
        "short_name": "Elsword",
        "path": 0,
        "version_added":0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "elsword",
        "class": "knight_emperor",
        "class_name": "Knight Emperor",
        "short_name": "KE",
        "job_names": ["Sword Knight", "Lord Knight", "Knight Emperor"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "hp%_pas", 24, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "hp%_pas", 4, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["alldmg_mod", 10, "mpattack_u", 10, "red_m", 18, "mpr_mod", 10, "critdmg_a", 8],
        "passive_hidden_pvp": ["alldmg_mod", 5, "mpattack_u", 5, "red_m", 4, "mpr_mod", 10, "critdmg_a", 8],
        "party_collection_stat": "tena",
        "party_collection_values": [0.5,1,1.5]
    },
    {
        "character": "elsword",
        "class": "rune_master",
        "class_name": "Rune Master",
        "short_name": "RM",
        "job_names": ["Magic Knight", "Rune Slayer", "Rune Master"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 15.75, "mdef": 21.7, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.25, "mdef": 15.3, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "mdef%_pas", 16, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "mdef%_pas", 8, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["specialdmg_mod", 10, "maxi_u", 15, "red_n", 19],
        "passive_hidden_pvp": ["maxi_u", 15, "red_n", 5],
        "party_collection_stat": "strength",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "elsword",
        "class": "immortal",
        "class_name": "Immortal",
        "short_name": "IM",
        "job_names": ["Sheath Knight", "Infinity Sword", "Immortal"],
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 18.3, "mdef": 24.7175, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15.3, "mdef": 14.25, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["as_m", 6, "ms_m", 15],
        "passive_hidden_pvp": ["as_m", 6, "ms_m", 15],
        "party_collection_stat": "brave",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "elsword",
        "class": "genesis",
        "class_name": "Genesis",
        "short_name": "Gen",
        "job_names": ["Root Knight", "Sacred Templar", "Genesis"],
        "path": 4,
        "version_added": 11,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["critdmg_a", 10, "crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["critdmg_a", 5, "crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "hyper",
        "party_collection_values": [3, 4, 5]
    },
    {
        "character": "aisha",
        "class": "aisha",
        "class_name": "Aisha",
        "short_name": "Aisha",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "aisha",
        "class": "aether_sage",
        "class_name": "Aether Sage",
        "short_name": "AeS",
        "job_names": ["High Magician", "Elemental Master", "Aether Sage"],
        "path": 1,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["cdr_mod", 10, "crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["cdr_mod", 10, "crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "matk",
        "party_collection_values": [100, 150, 200]
    },
    {
        "character": "aisha",
        "class": "oz_sorcerer",
        "class_name": "Oz Sorcerer",
        "short_name": "OZ",
        "job_names": ["Dark Magician", "Void Princess", "Oz Sorcerer"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 13.2, "mdef": 24.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 13.8, "mdef": 15.75, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["specialdmg_mod", 15, "crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["specialdmg_mod", 7.5, "crit_u", 15, "maxi_u", 15],
        "party_collection_stat": ["patk", "matk"],
        "party_collection_values": [50, 75, 100]
    },
    {
        "character": "aisha",
        "class": "metamorphy",
        "class_name": "Metamorphy",
        "short_name": "MtM",
        "job_names": ["Battle Magician", "Dimension Witch", "Metamorphy"],
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk":190.5, "matk": 29, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["critdmg_a", 10, "mpattack_m", 5, "mpattacked_m", 5, "crit_u", 15, "maxi_u", 15, "ms_m", 30, "dmg50", 20],
        "passive_hidden_pvp": ["critdmg_a", 10, "mpattack_m", 5, "mpattacked_m", 5, "crit_u", 15, "maxi_u", 15, "ms_m", 30, "dmg50", 10],
        "party_collection_stat": "patk",
        "party_collection_values": [100, 150, 200]
    },
    {
        "character": "aisha",
        "class": "lord_azoth",
        "class_name": "Lord Azoth",
        "short_name": "LA",
        "job_names": ["Wiz Magician", "Mystic Alchemist", "Lord Azoth"],
        "path": 4,
        "version_added": 15,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 21.7, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15.3, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["maxi_u", 15, "crit_u", 15],
        "passive_hidden_pvp": ["maxi_u", 15, "crit_u", 15],
        "party_collection_stat": "recitemcdr",
        "party_collection_values": [6, 8, 10]
    },
    {
        "character": "rena",
        "class": "rena",
        "class_name": "Rena",
        "short_name": "Rena",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "rena",
        "class": "anemos",
        "class_name": "Anemos",
        "short_name": "AN",
        "job_names": ["Combat Ranger", "Wind Sneaker", "Anemos"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 13.2, "mdef": 24.25, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 13.8, "mdef": 15.75, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "resall", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "resall", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["mpattack_m", 10, "mpattacked_m", 10, "as_m", 4, "red_m", 10],
        "passive_hidden_pvp": ["mpattack_m", 10, "mpattacked_m", 10, "as_m", 4, "red_m", 10],
        "party_collection_stat": "ms",
        "party_collection_values": [5, 6, 8]
    },
    {
        "character": "rena",
        "class": "daybreaker",
        "class_name": "Daybreaker",
        "short_name": "DaB",
        "job_names": ["Sniping Ranger", "Grand Archer", "Daybreaker"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 17.45, "mdef": 21.7, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 14.55, "mdef": 15.3, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["maxi_u", 15, "crit_u", 15, "alldmg_mod", 8, "mpattack_u", 20],
        "passive_hidden_pvp": ["maxi_u", 15, "crit_u", 15, "alldmg_mod", 8, "mpattack_u", 2],
        "party_collection_stat": "js",
        "party_collection_values": [5, 6, 8]
    },
    {
        "character": "rena",
        "class": "twilight",
        "class_name": "Twilight",
        "short_name": "TW",
        "job_names": ["Trapping Ranger", "Night Watcher", "Twilight"],
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "as",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "rena",
        "class": "prophetess",
        "class_name": "Prophetess",
        "short_name": "PR",
        "job_names": ["Poetic Ranger", "Tale Spinner", "Prophetess"],
        "path": 4,
        "version_added": 23,
        "attack_type": "magical",
        //mdef wrong
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 18.3, "mdef": 21.85, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 14.7, "mdef": 15.15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "alldmg",
        "party_collection_values": [0.5,0.75,1]
    },
    {
        "character": "raven",
        "class": "raven",
        "class_name": "Raven",
        "short_name": "Raven",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": ["awkt_m", 10],
        "passive_hidden_pvp": ["awkt_m", 10]
    },
    {
        "character": "raven",
        "class": "furious_blade",
        "class_name": "Furious Blade",
        "short_name": "FB",
        "job_names": ["Sword Taker", "Blade Master", "Furious Blade"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["awkt_m", 10, "as_u", 13, "crit_u", 15, "maxi_u", 15, "ms_m", 10, "specialdmg_mod", 23],
        "passive_hidden_pvp": ["awkt_m", 10, "as_u", 4, "crit_u", 15, "maxi_u", 15, "ms_m", 10, "specialdmg_mod", 11.5],
        "party_collection_stat": "flex",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "raven",
        "class": "rage_hearts",
        "class_name": "Rage Hearts",
        "short_name": "RH",
        "job_names": ["Over Taker", "Reckless Fist", "Rage Hearts"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 21.7, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15.3, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["awkt_m", 10, "red_n", 10, "mpattack_m", 10, "awkc_u", 16],
        "passive_hidden_pvp": ["awkt_m", 10, "red_n", 5, "mpattack_m", 5, "awkc_u", 4],
        "party_collection_stat": "command",
        "party_collection_values": [1, 1.5, 2]
    },
    {
        "character": "raven",
        "class": "nova_imperator",
        "class_name": "Nova Imperator",
        "short_name": "NI",
        "job_names": ["Weapon Taker", "Veteran Commander", "Nova Imperator"],
        "path": 3,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["awkt_m", 10, "mpattack_m", 15, "command_mod", 10],
        "passive_hidden_pvp": ["awkt_m", 10, "mpattack_m", 15, "command_mod", 5],
        "party_collection_stat": "dmghplost",
        "party_collection_values": [2, 3, 4]
    },
    {
        "character": "raven",
        "class": "revenant",
        "class_name": "Revenant",
        "short_name": "RV",
        "job_names": ["Venom Taker", "Mutant Reaper", "Revenant"],
        "path": 4,
        "version_added": 18,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 18.3, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15.3, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "pdef%_pas", 10, "mdef%_pas", 10, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "pdef%_pas", 5, "mdef%_pas", 5, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15, "awkt_m", 10, "critdmg_a", 15],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15, "awkt_m", 10, "critdmg_a", 7.5],
        "party_collection_stat": "add",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "eve",
        "class": "eve",
        "class_name": "Eve",
        "short_name": "Eve",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "eve",
        "class": "code_ultimate",
        "class_name": "Code: Ultimate",
        "short_name": "CU",
        "job_names": ["Code: Exotic", "Code: Nemesis", "Code: Ultimate"],
        "path": 1,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 21.7, "mdef": 15.75, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 15.3, "mdef": 14.25, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["ms_m", 12,"awkc_m", 10, "crit_m", 5],
        "passive_hidden_pvp": ["ms_m", 12, "awkc_m", 10, "crit_m", 5],
        "party_collection_stat": "matk%",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "eve",
        "class": "code_essencia",
        "class_name": "Code: Essencia",
        "short_name": "CEs",
        "job_names": ["Code: Architecture", "Code: Empress", "Code: Essencia"],
        "path": 2,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "ms_m", 10],
        "passive_hidden_pvp": ["crit_u", 15, "ms_m", 10],
        "party_collection_stat": "patk%",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "eve",
        "class": "code_sariel",
        "class_name": "Code: Sariel",
        "short_name": "CS",
        "job_names": ["Code: Electra", "Code: Battle Seraph", "Code: Sariel"],
        "path": 3,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 13.2, "mdef": 24.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 13.8, "mdef": 15.75, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "pdef%_pas", 20, "mdef%_pas", 20, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "pdef%_pas", 20, "mdef%_pas", 20, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["red_u", 10],
        "passive_hidden_pvp": ["red_u", 10],
        "party_collection_stat": ["patk%", "matk%"],
        "party_collection_values": [0.25, 0.5, 0.75]
    },
    {
        "character": "eve",
        "class": "code_antithese",
        "class_name": "Code: Antithese",
        "short_name": "CAnt",
        "job_names": ["Code: Unknown", "Code: Failess", "Code: Antithese"],
        "path": 4,
        "version_added": 13,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "critdmg_a", 20, "mpattack_n", 24, "red_n", 20],
        "passive_hidden_pvp": ["crit_u", 15, "critdmg_a", 12, "mpattack_n", 12, "red_n", 10],
        "party_collection_stat": "aadmg",
        "party_collection_values": [0.4,0.8,1.2]
    },
    {
        "character": "chung",
        "class": "chung",
        "class_name": "Chung",
        "short_name": "Chung",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "chung",
        "class": "comet_crusader",
        "class_name": "Comet Crusader",
        "short_name": "CC",
        "job_names": ["Fury Guardian", "Iron Paladin", "Comet Crusader"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 21.7, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15.3, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "resall", 100, "patk%_pas", 15, "hp%_pas", 10, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "resall", 50, "patk%_pas", 7.5, "hp%_pas", 5, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["mpattack_m", 6, "as_u", 8, "critres", 10, "ms_m", 10, "js_m", 10, "crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["mpattack_m", 6, "as_u", 8, "critres", 10, "ms_m", 10, "js_m", 10, "crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "awkc",
        "party_collection_values": [5, 6, 8]
    },
    {
        "character": "chung",
        "class": "fatal_phantom",
        "class_name": "Fatal Phantom",
        "short_name": "FP",
        "job_names": ["Shooting Guardian", "Deadly Chaser", "Fatal Phantom"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 17.45, "mdef": 21.7, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 14.55, "mdef": 15.3, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["as_m", 10, "crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["as_m", 10, "crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "awkt",
        "party_collection_values": [5, 6, 8]
    },
    {
        "character": "chung",
        "class": "centurion",
        "class_name": "Centurion",
        "short_name": "Cent",
        "job_names": ["Shelling Guardian", "Tactical Trooper", "Centurion"],
        "path": 3,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 4.8],
        "passive_hidden": ["maxi_u", 15, "crit_u", 15, "awkt_u", 30],
        "passive_hidden_pvp": ["maxi_u", 15, "crit_u", 15, "awkt_u", 30],
        "party_collection_stat": "bossred",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "chung",
        "class": "dius_aer",
        "class_name": "Dius Aer",
        "short_name": "DA",
        "job_names": ["Cor Guardian", "Divine Phanes", "Dius Aer"],
        "path": 4,
        "version_added": 28,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 7.5, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["as_u", 15, "ms_m", 10, "maxi_u", 15, "crit_u", 15, "specialdmg_mod", 20, "mpr_mod", 10],
        "passive_hidden_pvp": ["as_u", 15, "ms_m", 10, "maxi_u", 7.5, "crit_u", 7.5, "specialdmg_mod", 10, "mpr_mod", 10],
        "party_collection_stat": "as",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "ara",
        "class": "ara",
        "class_name": "Ara",
        "short_name": "Ara",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "ara",
        "class": "apsara",
        "class_name": "Apsara",
        "short_name": "Apsara",
        "job_names": ["Little Hsien", "Sakra Devanam", "Apsara"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6,  "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["as_m", 5, "ms_m", 5, "js_m", 5],
        "passive_hidden_pvp": ["as_m", 5, "ms_m", 5, "js_m", 5],
        "party_collection_stat": "pdef",
        "party_collection_values": [200, 300, 500]
    },
    {
        "character": "ara",
        "class": "devi",
        "class_name": "Devi",
        "short_name": "Devi",
        "job_names": ["Little Devil", "Yama Raja", "Devi"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": [],
        "passive_hidden_pvp": [],
        "party_collection_stat": "mdef",
        "party_collection_values": [200, 300, 500]
    },
    {
        "character": "ara",
        "class": "shakti",
        "class_name": "Shakti",
        "short_name": "Shakti",
        "job_names": ["Little Specter", "Asura", "Shakti"],
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["pdefpierce", 10, "mdefpierce", 10, "as_n", 10],
        "passive_hidden_pvp": ["pdefpierce", 10, "mdefpierce", 10, "as_n", 10],
        "party_collection_stat": "resall",
        "party_collection_values": [10, 20, 30]
    },
    {
        "character": "ara",
        "class": "surya",
        "class_name": "Surya",
        "short_name": "Surya",
        "job_names": ["Little Helper", "Marici", "Surya"],
        "path": 4,
        "version_added": 21,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 21.7, "mdef": 24.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15.3, "mdef": 15.75, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["awkt_m", 20, "awkc_m", 20, "ms_n", 20, "js_n", 20],
        "passive_hidden_pvp": ["awkt_m", 10, "awkc_m", 10, "ms_n", 8, "js_n", 8],
        "party_collection_stat": "exp",
        "party_collection_values": [1, 2, 3]
    },
    {
        "character": "elesis",
        "class": "elesis",
        "class_name": "Elesis",
        "short_name": "Elesis",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "elesis",
        "class": "empire_sword",
        "class_name": "Empire Sword",
        "short_name": "ES",
        "job_names": ["Saber Knight", "Grand Master", "Empire Sword"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["as_n", 5, "ms_n", 12],
        "passive_hidden_pvp": ["as_n", 5, "ms_n", 12],
        "party_collection_stat": "command",
        "party_collection_values": [1, 1.5, 2]
    },
    {
        "character": "elesis",
        "class": "flame_lord",
        "class_name": "Flame Lord",
        "short_name": "FL",
        "job_names": ["Pyro Knight", "Blazing Heart", "Flame Lord"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 15.75, "mdef": 21.7, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.25, "mdef": 15.3, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "resfir", 150, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "resfir", 150, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["critdmg_a", 15, "crit_u", 20, "maxi_u", 12],
        "passive_hidden_pvp": ["critdmg_a", 7.5, "crit_u", 20, "maxi_u", 12],
        "party_collection_stat": "elemall",
        "party_collection_values": [0.5, 1, 2]
    },
    {
        "character": "elesis",
        "class": "bloody_queen",
        "class_name": "Bloody Queen",
        "short_name": "BQ",
        "job_names": ["Dark Knight", "Crimson Avenger", "Bloody Queen"],
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 21.7, "mdef": 15.75, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15.3, "mdef": 14.25, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 18, "maxi_u", 20],
        "passive_hidden_pvp": ["crit_u", 18, "maxi_u", 20],
        "party_collection_stat": "dmghplost",
        "party_collection_values": [2, 3, 4]
    },
    {
        "character": "elesis",
        "class": "adrestia",
        "class_name": "Adrestia",
        "short_name": "AD",
        "job_names": ["Soar Knight", "Patrona", "Adrestia"],
        "path": 4,
        "version_added": 26,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "awkt",
        "party_collection_values": [5,6,8]
    },
    {
        "character": "add",
        "class": "add",
        "class_name": "Add",
        "short_name": "Add",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "add",
        "class": "doom_bringer",
        "class_name": "Doom Bringer",
        "short_name": "DB",
        "job_names": ["Psychic Tracer", "Lunatic Psyker", "Doom Bringer"],
        "path": 1,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 18.3, "mdef": 18.3, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.7, "mdef": 14.7, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["awkt_u", 25],
        "passive_hidden_pvp": ["awkt_u", 25],
        "party_collection_stat": "tenacdr",
        "party_collection_values": [1, 1.5, 2]
    },
    {
        "character": "add",
        "class": "dominator",
        "class_name": "Dominator",
        "short_name": "Dom",
        "job_names": ["Arc Tracer", "Mastermind", "Dominator"],
        "path": 2,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 13.2, "mdef": 24.25, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 13.8, "mdef": 15.75, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["maxi_u", 15],
        "passive_hidden_pvp": ["maxi_u", 15],
        "party_collection_stat": "strengthcdr",
        "party_collection_values": [1, 1.5, 2]
    },
    {
        "character": "add",
        "class": "mad_paradox",
        "class_name": "Mad Paradox",
        "short_name": "MP",
        "job_names": ["Time Tracer", "Diabolic Esper", "Mad Paradox"],
        "path": 3,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["as_m", 5, "awkt_u", 10, "crit_u", 15, "maxi_u", 15, "critdmg_a", 6],
        "passive_hidden_pvp": ["as_m", 5, "awkt_u", 10, "crit_u", 15, "maxi_u", 15, "critdmg_a", 6],
        "party_collection_stat": "bravecdr",
        "party_collection_values": [1, 1.5, 2]
    },
    {
        "character": "add",
        "class": "overmind",
        "class_name": "Overmind",
        "short_name": "OM",
        "job_names": ["Affect Tracer", "Dissembler", "Overmind"],
        "path": 4,
        "version_added": 25,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["as_m", 10, "ms_m", 10, "js_m", 10, "critdmg_a", 10, "mpr_mod", 10, "mpattack_m", 10, "mpattacked_m", 10],
        "passive_hidden_pvp": ["as_m", 10, "ms_m", 10, "js_m", 10, "critdmg_a", 5, "mpr_mod", 5, "mpattack_m", 5, "mpattacked_m", 5],
        "party_collection_stat": "mastercdr",
        "party_collection_values": [0.5, 1, 2]
    },
    {
        "character": "lu",
        "class": "lu",
        "class_name": "Lu",
        "short_name": "LuCiel",
        "combination_name": "LuCiel",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "lu",
        "class": "timoria",
        "class_name": "Timoria",
        "short_name": "Cat",
        "job_names": ["Chiliarch", "Dreadlord", "Catastrophe"],
        "combination_name": "Catastrophe",
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 21.7, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15.3, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["brave_mod", 12, "critdmg_a", 15, "crit_n", 15, "maxi_n", 15],
        "passive_hidden_pvp": ["brave_mod", 12, "critdmg_a", 7.5, "crit_n", 15, "maxi_n", 15],
        "party_collection_stat": "crit",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "lu",
        "class": "ishtar",
        "class_name": "Ishtar",
        "short_name": "IN",
        "job_names": ["Royal Guard", "Noblesse", "Innocent"],
        "combination_name": "Innocent",
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 17.45, "mdef": 21.7, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 14.55, "mdef": 15.3, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "resall", 137, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "resall", 50, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["brave_mod", 20, "crit_n", 15, "maxi_n", 15],
        "passive_hidden_pvp": ["brave_mod", 20, "crit_n", 15, "maxi_n", 15],
        "party_collection_stat": "maxi",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "lu",
        "class": "iblis",
        "class_name": "Iblis",
        "short_name": "DI",
        "job_names": ["Diabla", "Demonio", "Diangelion"],
        "combination_name": "Diangelion",
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 11.5, "mdef": 25.95, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 13.5, "mdef": 16.05, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["maxi_u", 15, "crit_n", 15],
        "passive_hidden_pvp": ["maxi_u", 15, "crit_n", 15],
        "party_collection_stat": "red",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "lu",
        "class": "nihilida",
        "class_name": "Nihilida",
        "short_name": "Dem",
        "job_names": ["Emptiness", "Turbids", "Demersio"],
        "combination_name": "Demersio",
        "path": 4,
        "version_added": 22,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 7.5, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15, "awkt_m", 10, "as_n", 10, "ms_n", 10],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15, "awkt_m", 10, "as_n", 10, "ms_n", 10],
        "party_collection_stat": "adapt",
        "party_collection_values": [0.5, 0.75, 1]
    },
    {
        "character": "ciel",
        "class": "ciel",
        "class_name": "Ciel",
        "short_name": "LuCiel",
        "combination_name": "LuCiel",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "ciel",
        "class": "abysser",
        "class_name": "Abysser",
        "short_name": "Cat",
        "job_names": ["Chiliarch", "Dreadlord", "Catastrophe"],
        "combination_name": "Catastrophe",
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 21.7, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15.3, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["brave_mod", 12, "critdmg_a", 15, "crit_n", 15, "maxi_n", 15],
        "passive_hidden_pvp": ["brave_mod", 12, "critdmg_a", 15, "crit_n", 15, "maxi_n", 15]
    },
    {
        "character": "ciel",
        "class": "chevalier",
        "class_name": "Chevalier",
        "short_name": "IN",
        "job_names": ["Royal Guard", "Noblesse", "Innocent"],
        "combination_name": "Innocent",
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 17.45, "mdef": 21.7, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 14.55, "mdef": 15.3, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "resall", 137, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "resall", 50, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["brave_mod", 20, "crit_n", 15, "maxi_n", 15],
        "passive_hidden_pvp": ["brave_mod", 20, "crit_n", 15, "maxi_n", 15]
    },
    {
        "character": "ciel",
        "class": "anular",
        "class_name": "Anular",
        "short_name": "DI",
        "job_names": ["Diabla", "Demonio", "Diangelion"],
        "combination_name": "Diangelion",
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 11.5, "mdef": 25.95, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 13.5, "mdef": 16.05, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["maxi_u", 15, "crit_n", 15],
        "passive_hidden_pvp": ["maxi_u", 15, "crit_n", 15]
    },
    {
        "character": "ciel",
        "class": "tyrannus",
        "class_name": "Tyrannus",
        "short_name": "Dem",
        "job_names": ["Emptiness", "Turbids", "Demersio"],
        "combination_name": "Demersio",
        "path": 4,
        "version_added": 22,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 7.5, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15, "awkt_m", 10, "as_n", 10, "ms_n", 10],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15, "awkt_m", 10, "as_n", 10, "ms_n", 10]
    },
    {
        "character": "rose",
        "class": "rose",
        "class_name": "Rose",
        "short_name": "Rose",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "rose",
        "class": "tempest_burster",
        "class_name": "Tempest Burster",
        "short_name": "TB",
        "job_names": ["Heavy Barrel", "Storm Trooper", "Tempest Burster"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": [],
        "passive_hidden_pvp": [],
        "party_collection_stat": "flex",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "rose",
        "class": "black_massacre",
        "class_name": "Black Massacre",
        "short_name": "BlM",
        "job_names": ["Bloodia", "Crimson Rose", "Black Massacre"],
        "path": 2,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 17.45, "mdef": 21.7, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 14.55, "mdef": 15.3, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": [],
        "passive_hidden_pvp": [],
        "party_collection_stat": "tena",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "rose",
        "class": "minerva",
        "class_name": "Minerva",
        "short_name": "MN",
        "job_names": ["Valkyrie", "Freyja", "Minerva"],
        "path": 3,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15, "airdmg_mod", 30, "as_m", 8, "ms_m", 8, "js_m", 8, "red_n", 20],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15, "airdmg_mod", 10, "as_m", 8, "ms_m", 8, "js_m", 8, "red_n", 10],
        "party_collection_stat": "strength",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "rose",
        "class": "prime_operator",
        "class_name": "Prime Operator",
        "short_name": "PO",
        "job_names": ["Metal Heart", "Optimus", "Prime Operator"],
        "path": 4,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15, "critdmg_a",20, "as_m", 10, "ms_m", 10, "js_m", 10],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15, "critdmg_a", 20, "as_m", 10, "ms_m", 10, "js_m", 1],
        "party_collection_stat": "brave",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "ain",
        "class": "ain",
        "class_name": "Ain",
        "short_name": "Ain",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "ain",
        "class": "richter",
        "class_name": "Richter",
        "short_name": "RI",
        "job_names": ["Lofty: Executor", "Arme Thaumaturgy", "Richter"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": ["critdmg_a", 15],
        "passive_hidden_pvp": ["critdmg_a", 7.5],
        "party_collection_stat": "awkc",
        "party_collection_values": [5, 6, 8]
    },
    {
        "character": "ain",
        "class": "bluhen",
        "class_name": "Bluhen",
        "short_name": "BL",
        "job_names": ["Lofty: Anpassen", "Erbluhen Emotion", "Bluhen"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["critdmg_a", 10],
        "passive_hidden_pvp": ["critdmg_a", 4],
        "party_collection_stat": "recitem",
        "party_collection_values": [2, 4, 6]
    },
    {
        "character": "ain",
        "class": "herrscher",
        "class_name": "Herrscher",
        "short_name": "HE",
        "job_names": ["Lofty: Wanderer", "Apostasia", "Herrscher"],
        "path": 3,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "matk%_pas", 6],
        "passive_hidden": ["as_m", 6],
        "passive_hidden_pvp": ["as_m", 6],
        "party_collection_stat": "bossdmg",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "ain",
        "class": "opferung",
        "class_name": "Opferung",
        "short_name": "Opf",
        "job_names": ["Lofty: Schreier", "Schatz Reprise", "Opferung"],
        "path": 4,
        "version_added": 29,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 21.7, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15.3, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 15],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "patk%_pas", 6],
        "passive_hidden": [],
        "passive_hidden_pvp": [],
        "party_collection_stat": "bossred",
        "party_collection_values": [2, 3, 5]
    },
    {
        "character": "laby",
        "class": "laby",
        "class_name": "Laby",
        "short_name": "Laby",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "laby",
        "class": "eternity_winner",
        "class_name": "Eternity Winner",
        "short_name": "EtW",
        "job_names": ["Sparky Child", "Rumble Pumn", "Eternity Winner"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["patk%_pas", 15, "maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["patk%_pas", 6, "maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["maxi_u", 15, "crit_u", 15, "critdmg_a", 15],
        "passive_hidden_pvp": ["maxi_u", 15, "crit_u", 15, "critdmg_a", 4.5],
        "party_collection_stat": "doubleatk",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "laby",
        "class": "radiant_soul",
        "class_name": "Radiant Soul",
        "short_name": "RaS",
        "job_names": ["Twinkle Child", "Shining Romantica", "Radiant Soul"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 182, "pdef": 15.75, "mdef": 24.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 78, "pdef": 14.25, "mdef": 15.75, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "resall", 100],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10, "resall", 100],
        "passive_hidden": ["awkc_u", 10],
        "passive_hidden_pvp": ["awkc_u", 10],
        "party_collection_stat": "matk%",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "laby",
        "class": "nisha_labyrinth",
        "class_name": "Nisha Labyrinth",
        "short_name": "NL",
        "job_names": ["Rusty Child", "Daydreamer", "Nisha Labyrinth"],
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 15.75, "mdef": 21.7, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 14.25, "mdef": 15.3, "hpflat": 2.5 },
        "passive": ["patk%_pas", 15, "maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["patk%_pas", 6, "maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["awkc_n", 20, "red_n", 12, "as_m", 7, "ms_m", 7, "js_m", 7, "crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["awkc_n", 20, "red_n", 2.4, "as_m", 7, "ms_m", 7, "js_m", 7, "crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "patk%",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "laby",
        "class": "twins_picaro",
        "class_name": "Twins Picaro",
        "short_name": "TP",
        "job_names": ["Rough Child", "Punky Poppet", "Twins Picaro"],
        "path": 4,
        "version_added": 24,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 20, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 15, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["matk%_pas", 15, "maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["matk%_pas", 6, "maxmp", 100, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "critdmg_a", 20, "maxi_u", 15],
        "passive_hidden_pvp": ["crit_u", 15, "critdmg_a", 12, "maxi_u", 15],
        "party_collection_stat": "mpr",
        "party_collection_values": [1, 1.5, 2]
    },
    {
        "character": "noah",
        "class": "noah",
        "class_name": "Noah",
        "short_name": "Noah",
        "path": 0,
        "version_added": 0,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "noah",
        "class": "liberator",
        "class_name": "Liberator",
        "short_name": "Lib",
        "job_names": ["Second Revenger", "Silent Shadow", "Liberator"],
        "path": 1,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "pdef%_pas", 18, "mdef%_pas", 18, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "pdef%_pas", 9, "mdef%_pas", 9, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": [],
        "passive_hidden_pvp": [],
        "party_collection_stat": "critdmg",
        "party_collection_values": [0.5, 1, 1.5]
    },
    {
        "character": "noah",
        "class": "celestia",
        "class_name": "Celestia",
        "short_name": "Cel",
        "job_names": ["Second Selection", "Stellar Caster", "Celestia"],
        "path": 2,
        "version_added": 0,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["as_n", 15, "critdmg_a", 20],
        "passive_hidden_pvp": ["as_n", 15, "critdmg_a", 8],
        "party_collection_stat": "mdefignore",
        "party_collection_values": [0.4, 0.8, 1.2]
    },
    {
        "character": "noah",
        "class": "nyx_pieta",
        "class_name": "Nyx Pieta",
        "short_name": "Nyx",
        "job_names": ["Second Grief", "Pale Pilgrim", "Nyx Pieta"],
        "path": 3,
        "version_added": 0,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15,"patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6,"patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15, "bossred_m", 5],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15, "bossred_m", 5],
        "party_collection_stat": "pdefignore",
        "party_collection_values": [0.4, 0.8, 1.2]
    },
    {
        "character": "noah",
        "class": "morpheus",
        "class_name": "Morpheus",
        "short_name": "Mor",
        "job_names": ["Second Dejection", "Hazy Delusion", "Morpheus"],
        "path": 4,
        "version_added": 29,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 10, "maxi_u", 10, "awkc_m", 30],
        "passive_hidden_pvp": ["crit_u", 10, "maxi_u", 10, "awkc_m", 15],
        "party_collection_stat": ["patk", "matk"],
        "party_collection_values": [50,75,100]
    },
    {
        "character": "lithia",
        "class": "lithia",
        "class_name": "Lithia",
        "short_name": "Lithia",
        "path": 0,
        "version_added": 31,
        "attack_type": "average",
        "modifier_fix": { "patk": 29, "matk": 29, "pdef": 7.25, "mdef": 7.25, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 51, "pdef": 12.75, "mdef": 12.75, "hpflat": 0 },
        "passive": [],
        "passive_pvp": [],
        "passive_hidden": [],
        "passive_hidden_pvp": []
    },
    {
        "character": "lithia",
        "class": "gembliss",
        "class_name": "Gembliss",
        "short_name": "GB",
        "job_names": ["Poten Finder", "Mighty Miner", "Gembliss"],
        "path": 1,
        "version_added": 31,
        "attack_type": "physical",
        "modifier_fix": { "patk": 190.5, "matk": 29, "pdef": 20, "mdef": 17.45, "hpflat": 1 },
        "modifier_scale": { "patk": 79.5, "matk": 51, "pdef": 15, "mdef": 14.55, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "critdmg_a", 20, "maxi_u", 15],
        "passive_hidden_pvp": ["crit_u", 15, "critdmg_a", 20, "maxi_u", 15],
        "party_collection_stat": "idr",
        "party_collection_values": [1,2,3]
    },
    {
        "character": "lithia",
        "class": "avarice",
        "class_name": "Avarice",
        "short_name": "AV",
        "job_names": ["Fortune Finder", "Greedy Wonder", "Avarice"],
        "path": 2,
        "version_added": 33,
        "attack_type": "physical",
        "modifier_fix": { "patk": 182, "matk": 29, "pdef": 20, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 78, "matk": 51, "pdef": 15, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "patk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "patk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "ed",
        "party_collection_values": [1, 2, 3]
    },
    {
        "character": "lithia",
        "class": "achlys",
        "class_name": "Achlys",
        "short_name": "AC",
        "job_names": ["Path Finder", "Rima Clavic", "Achlys"],
        "path": 3,
        "version_added": 34,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "critdmg_a", 20, "maxi_u", 15],
        "passive_hidden_pvp": ["crit_u", 15, "critdmg_a", 20, "maxi_u", 15],
        "party_collection_stat": "hyper",
        "party_collection_values": [3,4,5]
    },
    {
        "character": "lithia",
        "class": "mischief",
        "class_name": "Mischief",
        "short_name": "MC",
        "job_names": ["Trick Finder", "Cynical Sneer", "Mischief"],
        "path": 4,
        "version_added": 34,
        "attack_type": "magical",
        "modifier_fix": { "patk": 29, "matk": 190.5, "pdef": 17.45, "mdef": 20, "hpflat": 1 },
        "modifier_scale": { "patk": 51, "matk": 79.5, "pdef": 14.55, "mdef": 15, "hpflat": 2.5 },
        "passive": ["maxmp", 100, "matk%_pas", 15, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_pvp": ["maxmp", 100, "matk%_pas", 6, "patk%_pas", 10, "matk%_pas", 10, "pdef%_pas", 10, "mdef%_pas", 10, "hp%_pas", 10],
        "passive_hidden": ["crit_u", 15, "maxi_u", 15],
        "passive_hidden_pvp": ["crit_u", 15, "maxi_u", 15],
        "party_collection_stat": "master",
        "party_collection_values": [2,3,4]
    }

]

equip_characters_synergies = [
    {
        "id":0,
        "name":"1st Path",
        "required_class": ["knight_emperor", "aether_sage", "anemos", "furious_blade", "code_ultimate", "comet_crusader", "apsara", "empire_sword", "doom_bringer", "timoria", "tempest_burster", "richter", "eternity_winner", "liberator", "gembliss"],
        "required_stage":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        "required_count":[3,6],
        "bonus": [["alldmg", 3], ["alldmg", 5,"When using an Active Force Skill, casts Diffused Wonder Wall (Cooldown 30s)",0]],
        "apply": [1,0]
    },
    {
        "id": 1,
        "name": "2nd Path",
        "required_class": ["rune_master", "oz_sorcerer", "daybreaker", "rage_hearts", "code_essencia", "fatal_phantom", "devi", "flame_lord", "dominator", "ishtar", "black_massacre", "bluhen", "radiant_soul", "celestia", "avarice"],
        "required_stage": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "required_count": [3, 6],
        "bonus": [["alldmg", 3], ["alldmg", 5, "When using an Active Force Skill, casts Cloudy Sunshower (Cooldown 15s)", 0]],
        "apply": [2, 0]
    },
    {
        "id": 2,
        "name": "3rd Path",
        "required_class": ["immortal", "metamorphy", "twilight", "nova_imperator", "code_sariel", "centurion", "shakti", "bloody_queen", "mad_paradox", "iblis", "minerva", "herrscher", "nisha_labyrinth", "nyx_pieta", "achlys"],
        "required_stage": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "required_count": [3, 6],
        "bonus": [["alldmg", 3], ["alldmg", 5, "When using an Active Force Skill, casts Broken Seal of Time (Cooldown 30s)", 0]],
        "apply": [3, 0]
    },
    {
        "id": 3,
        "name": "4th Path",
        "required_class": ["genesis", "lord_azoth", "prophetess", "revenant", "code_antithese", "dius_aer", "surya", "adrestia", "overmind", "nihilida", "prime_operator", "opferung", "twins_picaro", "morpheus", "mischief"],
        "required_stage": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "required_count": [3, 6],
        "bonus": [["alldmg", 3], ["alldmg", 5]],
        "apply": [4, 0]
    },
    {
        "id": 4,
        "name": "Mechanical Engineering",
        "required_class": ["prime_operator"],
        "required_stage": [2],
        "required_count": [1],
        "bonus": [["mastercdr", 5]]
    },
    {
        "id": 5,
        "name": "Sharp",
        "required_class": ["genesis", "daybreaker", "code_ultimate", "code_antithese", "flame_lord", "adrestia", "ishtar", "tempest_burster", "eternity_winner", "nyx_pieta", "achlys"],
        "required_stage": [2, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3],
        "required_count": [3, 6],
        "bonus": [["aadmg", 3], ["aadmg", 5]]
    },
    {
        "id": 6,
        "name": "Nasod Research",
        "required_class": ["code_ultimate", "code_essencia", "code_sariel", "dominator", "gembliss"],
        "required_stage": [2, 2, 2, 3, 3, 2],
        "required_count": [2, 4],
        "bonus": [["cdr", 2], ["cdr", 4]]
    },
    {
        "id": 7,
        "name": "Blessing of Spirit",
        "required_class": ["anemos", "daybreaker", "twilight", "prophetess"],
        "required_stage": [2, 2, 2, 2],
        "required_count": [2],
        "bonus": [["hpflat", 80000]],
        "pvp_bonus": [["hpflat", 32000]]
    },
    {
        "id": 8,
        "name": "Physical Specialist",
        "required_class": ["metamorphy", "twilight", "revenant", "overmind", "timoria", "black_massacre", "nisha_labyrinth", "liberator", "avarice"],
        "required_stage": [2, 3, 3, 3, 3, 2, 2, 3, 2],
        "required_count": [2, 4],
        "bonus": [["patk%", 1], ["patk%", 3]]
    },
    {
        "id": 9,
        "name": "Magical Specialist",
        "required_class": ["rune_master", "prophetess", "rage_hearts", "fatal_phantom", "doom_bringer", "bluhen", "twins_picaro", "achlys"],
        "required_stage": [3, 3, 2, 3, 2, 2, 2, 2],
        "required_count": [2, 4],
        "bonus": [["matk%", 1], ["matk%", 3]]
    },
    {
        "id": 10,
        "name": "Accomplished Steps",
        "required_class": ["apsara"],
        "required_stage": [3],
        "required_count": [1],
        "bonus": [["idr", 8]]
    },
    {
        "id": 11,
        "name": "Abundant Steps",
        "required_class": ["devi"],
        "required_stage": [3],
        "required_count": [1],
        "bonus": [["ed", 7]]
    },
    {
        "id": 12,
        "name": "Adept Steps",
        "required_class": ["shakti"],
        "required_stage": [3],
        "required_count": [1],
        "bonus": [["exp", 10]]
    },
    {
        "id": 13,
        "name": "Step of Communion",
        "required_class": ["surya"],
        "required_stage": [3],
        "required_count": [1],
        "bonus": [["recitem", 8]]
    },
    {
        "id": 14,
        "name": "Agile",
        "required_class": ["immortal", "anemos", "furious_blade", "fatal_phantom", "adrestia", "minerva", "liberator"],
        "required_stage": [2, 3, 3, 2, 2, 2, 2],
        "required_count": [2, 4],
        "bonus": [["as", 3, "ms", 3, "js", 3], ["as", 6, "ms", 6, "js", 6]]
    },
    {
        "id": 15,
        "name": "Bringer of Justice",
        "required_class": ["knight_emperor", "genesis", "comet_crusader", "apsara", "empire_sword", "richter"],
        "required_stage": [3, 3, 2, 2, 3, 2],
        "required_count": [2, 4],
        "bonus": [["pdef%", 4, "mdef%", 4], ["pdef%", 8, "mdef%", 8]]
    },
    {
        "id": 16,
        "name": "Fist Fight",
        "required_class": ["rage_hearts", "doom_bringer", "eternity_winner"],
        "required_stage": [3, 3, 2],
        "required_count": [2],
        "bonus": [["dmg50", 2]]
    },
    {
        "id": 17,
        "name": "Time and Space",
        "required_class": ["metamorphy", "mad_paradox", "herrscher"],
        "required_stage": [3, 2, 2],
        "required_count": [2],
        "bonus": [["pdefignore", 2, "mdefignore", 2]]
    },
    {
        "id": 18,
        "name": "Demon",
        "required_class": ["timoria", "ishtar", "iblis", "nihilida"],
        "required_stage": [2, 2, 2, 2],
        "required_count": [3],
        "bonus": [["adapt", 2]]
    },
    {
        "id": 19,
        "name": "Titan Slayer",
        "required_class": ["immortal", "nova_imperator", "centurion", "tempest_burster", "richter", "celestia", "morpheus", "gembliss"],
        "required_stage": [3, 3, 3, 3, 3, 3, 2, 3],
        "required_count": [2,4,5],
        "bonus": [["dmg50+", 2], ["dmg50+", 3], ["dmg50+", 5]]
    },
    {
        "id": 20,
        "name": "Blessing of Mana",
        "required_class": ["oz_sorcerer", "shakti", "radiant_soul"],
        "required_stage": [2, 2, 2],
        "required_count": [2,3],
        "bonus": [["maxmp", 20], ["maxmp", 30]]
    },
    {
        "id": 21,
        "name": "Researcher",
        "required_class": ["aether_sage", "lord_azoth", "code_essencia", "centurion", "dominator", "overmind", "prime_operator", "celestia"],
        "required_stage": [2, 2, 3, 2, 2, 2, 3, 2],
        "required_count": [2, 5],
        "bonus": [["10% chance to gain 1 additional title count", 0], ["20% chance to gain 1 additional title count", 0]]
    },
    {
        "id": 22,
        "name": "Instinctual Movement",
        "required_class": ["knight_emperor", "furious_blade", "empire_sword"],
        "required_stage": [2, 2, 2],
        "required_count": [3],
        "bonus": [["Elsword, Raven, and Elesis gain a double jump", 0]]
    },
    {
        "id": 23,
        "name": "One Who Yearns",
        "required_class": ["oz_sorcerer", "lord_azoth", "revenant", "devi", "bloody_queen", "mad_paradox", "iblis", "black_massacre", "herrscher", "opferung", "mischief"],
        "required_stage": [3, 3, 2, 2, 3, 3, 3, 3, 3, 2, 2],
        "required_count": [3, 5],
        "bonus": [["hyper", 60], ["hyper", 80]]
    },
    {
        "id": 24,
        "name": "Attribute Master",
        "required_class": ["rune_master", "aether_sage", "comet_crusader", "flame_lord"],
        "required_stage": [2, 3, 3, 2],
        "required_count": [2, 4],
        "bonus": [["resall", 30], ["resall", 60]]
    },
    {
        "id": 25,
        "name": "It's Fine Cuz It Hurts",
        "required_class": ["nova_imperator", "dius_aer", "surya", "bloody_queen", "nihilida", "radiant_soul", "bluhen", "nyx_pieta", "avarice"],
        "required_stage": [2, 2, 2, 2, 3, 3, 3, 2, 3],
        "required_count": [2, 4],
        "bonus": [["recitem", 2], ["recitem", 4, "Upon taking fatal damage, gain 1 HP and become invincible for 3 seconds (Cooldown 180s)", 0]]
    },
    {
        "id": 26,
        "name": "Laby's Friend",
        "required_class": ["nisha_labyrinth"],
        "required_stage": [3],
        "required_count": [1],
        "bonus": [["expartifact", 25]]
    },
    {
        "id": 27,
        "name": "Angel of the Battlefield",
        "required_class": ["code_sariel", "dius_aer", "minerva"],
        "required_stage": [3, 3, 3],
        "required_count": [2],
        "bonus": [["airdmg", 4]]
    },
    {
        "id": 28,
        "name": "Distorted Gaze",
        "required_class": ["code_antithese", "opferung", "morpheus", "mischief"],
        "required_stage": [3, 3, 3, 3],
        "required_count": [2],
        "bonus": [["acdmg", 2]]
    },
    {
        "id": 29,
        "name": "King of Pranks ",
        "required_class": ["twins_picaro"],
        "required_stage": [3],
        "required_count": [1],
        "bonus": [["Make sure you apologize after doing something bad!", 0]]
    }
]


